// Signup - Criar cadastro de usuário
POST http://localhost:3003/signup
Content-Type: application/json

{

    "name":"Bianca Paccola",
    "email":"bianca.paccola@gmail.com",
    "password":"123abc#"
}

###

// Login
POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "bianca.paccola@gmail.com",
    "password": "w5glbr6"

}

###

// Criar receita
POST http://localhost:3003/recipe
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMyNWExNThiLTE1NzEtNDYyMC1iZGVkLWNjODliZTQyNWQ2NSIsImlhdCI6MTY3NjQxMjc5OCwiZXhwIjoxNjc2NDI3MTk4fQ.8tEMuwDXX7Q2770l30RY4lyIZK2BF4XwI1jXS6f0YDE

{
    "title": "Bolo de banana",
    "description": "banana aveia canela acucar"

}

###

// Esqueci a senha
PUT http://localhost:3003/forgot-password
Content-Type: application/json

{
    "email": "bianca.paccola@gmail.com"
}