// Signup - Criar cadastro de usuário
POST http://localhost:3003/signup
Content-Type: application/json

{

    "name":"Bianca Paccola",
    "email":"bianca@email.com",
    "password":"123abc#"
}

###

// Login
POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "bianca@email.com",
    "password": "123abc#"

}