// Signup - Criar cadastro de usuário
POST http://localhost:3003/signup
Content-Type: application/json

{

    "name":"Bianca Paccola",
    "email":"bianca.paccola@gmail.com",
    "password":"123abc#"
}

###
// Retorna todos os usuários cadastrados no banco de dados
GET http://localhost:3003/all

###


// Login
POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "bianca.paccola@gmail.com",
    "password": "w5glbr6"
}
// Criar receitas
###

// Criar receita
POST http://localhost:3003/recipe
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk5ZDQyZTcwLWQ5NWUtNDdhYy1hOGY4LTFmMTBlYWUyMmY4ZiIsImlhdCI6MTY3NjUxMzU2MywiZXhwIjoxNjc2NTI3OTYzfQ.57tIymx6FtxvsuuheQHmfh4mK-WDHI1cUU2sfR0_2gM

{
    "title": "Brigadeiro",
    "description": "Misture uma colher de manteiga com uma caixa de leite condensado, quatro colheres de achocolatado e misture até desgrudar da panela"
}

###

// Retorna os dados de um seguidor com autorização.
POST http://localhost:3003/follow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk5ZDQyZTcwLWQ5NWUtNDdhYy1hOGY4LTFmMTBlYWUyMmY4ZiIsImlhdCI6MTY3NjU4OTkwMSwiZXhwIjoxNjc2NjA0MzAxfQ.ByBArZVRpdjDoO1Ul3vvpCwOP5um09NPwO5Adar0Cew

{
    "followId":"72f25832-3249-44d3-bb14-5de2ec7da0d2"
}


###
// Esqueci a senha
PUT http://localhost:3003/forgot-password
Content-Type: application/json

{
    "email": "bianca.paccola@gmail.com"

}

###

// Retorna dados confidenciais de um usuário com a autorização concedida pelo token.
GET http://localhost:3003/user
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA0MmVlMGIwLTM1NDEtNDlmYy05MTg2LTQ4M2UxMmRjNGM2NyIsImlhdCI6MTY3NjU4NDA5MCwiZXhwIjoxNjc2NTk4NDkwfQ.HX4UKBaHhfOsnEr16sAsnNE--2Od3ef_BpfZmSCIOI8
###

// Obtenha as receitas de um usuário específico utilizando o seu token de acesso.
GET http://localhost:3003/all-recipes
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk5ZDQyZTcwLWQ5NWUtNDdhYy1hOGY4LTFmMTBlYWUyMmY4ZiIsImlhdCI6MTY3NjUxMzU2MywiZXhwIjoxNjc2NTI3OTYzfQ.57tIymx6FtxvsuuheQHmfh4mK-WDHI1cUU2sfR0_2gM


###

// Retornar a lista de relações entre quem segue e quem é seguido.
GET http://localhost:3003/all-followers
Content-Type: application/json

###

GET http://localhost:3003/my-feed 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk5ZDQyZTcwLWQ5NWUtNDdhYy1hOGY4LTFmMTBlYWUyMmY4ZiIsImlhdCI6MTY3NjU4OTkwMSwiZXhwIjoxNjc2NjA0MzAxfQ.ByBArZVRpdjDoO1Ul3vvpCwOP5um09NPwO5Adar0Cew